#!/usr/bin/env python3
"""Reject Antigravity git commits that violate the shared commit-message policy."""

from __future__ import annotations

import json
import re
import shlex
import subprocess
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path


class ValidationError(Exception):
    pass


SUBJECT_PATTERN = re.compile(
    r"^(?P<type>[a-z]+)(?P<breaking>!)?\((?P<scope>[a-z0-9-]+)\): (?P<description>.+)$"
)
BREAKING_CHANGE_PATTERN = re.compile(r"^BREAKING CHANGE: .+", re.MULTILINE)
AI_METADATA_PATTERN = re.compile(
    r"(?:^|\n)(?:co-authored-by:.*(?:antigravity|gemini|codex|chatgpt|claude|openai)|made[- ]with:|generated by:|ai[- ]generated:)|"
    r"(?:made with|generated by)\s+(?:antigravity|gemini|codex|chatgpt|claude|openai)",
    re.IGNORECASE,
)
NON_IMPERATIVE_STARTS = {
    "added", "adds", "fixed", "fixes", "updated", "updates", "removed", "removes",
    "refactored", "refactors", "changed", "changes", "implemented", "implements",
}
GIT_OPTIONS_WITH_VALUES = {"-C", "-c", "--git-dir", "--work-tree", "--namespace", "--super-prefix"}
UNSUPPORTED_MESSAGE_OPTIONS = {"-F", "--file", "--reuse-message", "-C", "--reedit-message", "-c", "--fixup", "--squash"}
BODY_BULLET_PATTERN = re.compile(r"^- (?P<label>[a-z-]+): (?P<detail>.+)$")
ANSI_C_QUOTED_PATTERN = re.compile(r"\$'((?:\\.|[^'])*)'", re.DOTALL)


@dataclass(frozen=True)
class ChangeSize:
    files: int
    lines: int

    @property
    def tier(self) -> str:
        if self.files <= 2 and self.lines <= 50:
            return "small"
        if self.files <= 5 and self.lines <= 200:
            return "medium"
        return "large"


@dataclass(frozen=True)
class CommitSubject:
    commit_type: str
    is_breaking: bool


def block(reason: str) -> None:
    raise ValidationError(reason)


def decode_ansi_c_quoted(match: re.Match[str]) -> str:
    """Convert the Bash ANSI-C quote subset used for multiline -m values."""
    escapes = {"n": "\n", "r": "\r", "t": "\t", "\\": "\\", "'": "'", '"': '"'}
    content = match.group(1)
    decoded: list[str] = []
    index = 0
    while index < len(content):
        character = content[index]
        if character == "\\" and index + 1 < len(content):
            index += 1
            decoded.append(escapes.get(content[index], content[index]))
        else:
            decoded.append(character)
        index += 1
    return shlex.quote("".join(decoded))


def split_shell_command(command: str) -> list[list[str]]:
    """Split simple shell pipelines into token lists without executing them."""
    try:
        tokens = shlex.split(ANSI_C_QUOTED_PATTERN.sub(decode_ansi_c_quoted, command), posix=True)
    except ValueError:
        block("Commit command must use valid shell quoting and explicit -m arguments.")

    commands: list[list[str]] = [[]]
    for token in tokens:
        if token in {"&&", "||", ";", "|"}:
            commands.append([])
        else:
            commands[-1].append(token)
    return [part for part in commands if part]


def find_git_commit_arguments(tokens: Sequence[str]) -> list[str] | None:
    """Return arguments after `git commit` for a simple shell command."""
    index = 0
    while index < len(tokens) and re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", tokens[index]):
        index += 1
    if index < len(tokens) and tokens[index] == "command":
        index += 1
    if index >= len(tokens) or tokens[index] != "git":
        return None
    index += 1

    while index < len(tokens):
        token = tokens[index]
        if token == "commit":
            return list(tokens[index + 1 :])
        if token == "--":
            return None
        if token in GIT_OPTIONS_WITH_VALUES:
            index += 2
            continue
        if token.startswith("--git-dir=") or token.startswith("--work-tree=") or token.startswith("--namespace="):
            index += 1
            continue
        if token.startswith("-"):
            index += 1
            continue
        return None
    return None


def extract_messages(arguments: Sequence[str]) -> list[str]:
    """Extract explicit -m/--message values and reject opaque message sources."""
    messages: list[str] = []
    index = 0
    while index < len(arguments):
        argument = arguments[index]
        if argument in UNSUPPORTED_MESSAGE_OPTIONS:
            block(f"Unsupported git commit option {argument}; use explicit -m arguments instead.")
        if argument.startswith("--file=") or argument.startswith("--reuse-message=") or argument.startswith("--reedit-message="):
            block("Unsupported git commit message source; use explicit -m arguments instead.")
        if argument in {"-m", "--message"}:
            if index + 1 >= len(arguments) or not arguments[index + 1].strip():
                block(f"{argument} requires a non-empty message.")
            messages.append(arguments[index + 1])
            index += 2
            continue
        if argument.startswith("--message="):
            message = argument.removeprefix("--message=")
            if not message.strip():
                block("--message requires a non-empty message.")
            messages.append(message)
            index += 1
            continue
        if argument.startswith("-m") and argument != "-m":
            message = argument[2:]
            if not message.strip():
                block("-m requires a non-empty message.")
            messages.append(message)
        index += 1

    if not messages:
        block("Antigravity git commits must use an explicit -m subject (and optional additional -m body arguments).")
    return messages


def validate_subject(subject: str) -> CommitSubject:
    if "\n" in subject:
        block("The first -m value must contain only the commit subject.")
    if len(subject) > 50:
        block("Commit subject must be 50 characters or fewer.")
    if subject.endswith("."):
        block("Commit subject must not end with a period.")

    match = SUBJECT_PATTERN.fullmatch(subject)
    if not match:
        block("Commit subject must match <type>[!](<scope>): <short-description> with lowercase type and scope.")

    first_word = match.group("description").split(maxsplit=1)[0].lower()
    if first_word in NON_IMPERATIVE_STARTS:
        block("Commit subject description must use the imperative mood (for example, 'add' instead of 'added').")
    return CommitSubject(match.group("type"), bool(match.group("breaking")))


def required_body_labels(commit_type: str, tier: str) -> set[str]:
    if commit_type in {"docs", "chore"}:
        requirements = {
            "small": {"why"},
            "medium": {"what", "why"},
            "large": {"what", "why", "verification"},
        }
    elif commit_type in {"feat", "fix"}:
        requirements = {
            "small": {"what", "why"},
            "medium": {"what", "why", "impact"},
            "large": {"what", "why", "impact", "tests"},
        }
    else:
        requirements = {"small": {"what", "why"}, "medium": {"what", "why"}, "large": {"what", "why"}}
    return requirements[tier]


def get_change_size(cwd: str) -> ChangeSize:
    """Measure the staged change that the pending commit will record."""
    try:
        result = subprocess.run(
            ["git", "-C", cwd, "diff", "--cached", "--numstat"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return ChangeSize(0, 0)

    files = 0
    lines = 0
    for line in result.stdout.splitlines():
        additions, deletions, _ = line.split("\t", maxsplit=2)
        files += 1
        if additions.isdigit():
            lines += int(additions)
        if deletions.isdigit():
            lines += int(deletions)
    return ChangeSize(files, lines)


def validate_body(messages: Sequence[str], subject: CommitSubject, change_size: ChangeSize) -> None:
    if len(messages) != 2:
        block("Every commit must use exactly one -m subject and one -m body; separate body bullets with newlines, not additional -m arguments.")
    body = messages[1]
    if AI_METADATA_PATTERN.search("\n".join(messages)):
        block("Commit message must not include AI signatures or tool-specific metadata.")
    if not body:
        block("Every commit must include a body in an additional -m argument.")

    lines = body.splitlines()
    if any(not line for line in lines):
        block("Commit body must not contain blank lines; keep labeled bullets consecutive.")
    if any(len(line) > 72 for line in lines):
        block("Commit body lines must be 72 characters or fewer.")
    labels: set[str] = set()
    for line in lines:
        if not line:
            continue
        if line.startswith("BREAKING CHANGE: "):
            continue
        match = BODY_BULLET_PATTERN.fullmatch(line)
        if not match or len(match.group("detail").strip()) < 8:
            block("Commit body lines must use '- <label>: <meaningful detail>' bullets.")
        labels.add(match.group("label"))

    missing_labels = required_body_labels(subject.commit_type, change_size.tier) - labels
    if missing_labels:
        required = ", ".join(sorted(missing_labels))
        block(f"{subject.commit_type} {change_size.tier} changes require body labels: {required}.")
    if subject.is_breaking and not BREAKING_CHANGE_PATTERN.search(body):
        block("Breaking changes require a BREAKING CHANGE: footer in the commit body.")


def respond(decision: str, reason: str | None = None) -> None:
    payload: dict[str, str] = {"decision": decision}
    if reason:
        payload["reason"] = reason
    print(json.dumps(payload))
    sys.exit(0)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        respond("allow")

    tool_call = payload.get("toolCall", {})
    if tool_call.get("name") != "run_command":
        respond("allow")

    args = tool_call.get("args", {})
    command = args.get("CommandLine")
    if not isinstance(command, str):
        respond("allow")

    cwd = args.get("Cwd")
    if not cwd:
        workspace_paths = payload.get("workspacePaths", [])
        cwd = workspace_paths[0] if workspace_paths else "."

    try:
        for tokens in split_shell_command(command):
            arguments = find_git_commit_arguments(tokens)
            if arguments is None:
                continue
            messages = extract_messages(arguments)
            validate_body(messages, validate_subject(messages[0]), get_change_size(cwd))
    except ValidationError as err:
        respond("deny", str(err))

    respond("allow")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
